dist: xenial
language: node_js

before_install:
  - npm i -g npm
  - npm i -g firebase firebase-tools

install:
  - npm --prefix="havedonewilldo-ui" ci

script:
  - |
    if [[ $TRAVIS_BRANCH =~ ^(master)$ ]]; then
      firebase deploy --token "$FIREBASE_TOKEN"
    fi
